#!/usr/bin/env ruby
# -*- coding: utf-8 -*-

require 'cgi'
require 'json'

require 'web_analytics_discovery/grabberutils'
include GrabberUtils

TEMPLATES = [
	'Шаблон:Посещаемость_по_данным_Compete',
	'Шаблон:Посещаемость_по_данным_LiveInternet',
	'Шаблон:Посещаемость_по_данным_Mail.ru',
	'Шаблон:Посещаемость_по_данным_Openstat',
	'Шаблон:Посещаемость_по_данным_Quantcast',
	'Шаблон:Посещаемость_по_данным_Rambler',
]

FileUtils::mkdir_p('lists')

TEMPLATES.each { |t|
	d = download("http://ru.wikipedia.org/w/api.php?action=query&list=embeddedin&eititle=#{CGI::escape(t)}&eilimit=500&format=json")
	j = JSON.load(d)
	File.open("lists/#{t}", 'w') { |f|
		j['query']['embeddedin'].each { |x|
			# Only process main namespace
			next unless x['ns'] == 0
			f.puts x['title']
		}
	}
}
