#!/usr/bin/env ruby
# -*- coding: utf-8 -*-

require 'cgi'
require 'json'

require 'optparse'
require 'web_analytics_discovery'
require 'media_wiki'
require 'logger'

begin
	require_relative 'config'
rescue LoadError
	$stderr.puts <<__EOF__
You must create config file 'config.rb' with bot credentials to use this utility. Fill this template:

BOT_LOGIN = ''
BOT_PASSWORD = ''
__EOF__
	exit 1
end

include WebAnalyticsDiscovery

class Processor
	class NoDataFromGrabber < Exception; end
	class NoTemplateFound < Exception; end

	COMMENT = '<!-- обновляется ежемесячно ботом -->'

	def initialize(grabber, tmpl)
		@grabber = grabber
		@tmpl = tmpl
	end

	def process(src)
		found = false
		dest = src.gsub(/\{\{\s*#{@tmpl}\s*\|\s*([^{}|]+?)\s*\}\}/m) { |x|
			found = true
			template_call_with_data($1)
		}

		raise NoTemplateFound.new unless found
		return dest
	end

	def template_call_with_data(id)
		stat = @grabber.run_id(id)

		# Check that we've got data we need
		raise NoDataFromGrabber.new unless stat[:visitors_mon]

		"{{#{@tmpl}|#{id}|#{humanize(stat[:visitors_mon])} посетителей/месяц #{COMMENT}}}"
	end

	def humanize(number)
		if number < 1_000
			number.to_s
		elsif number < 1_000_000
			sprintf '%.1f тыс.', number.to_f / 1_000
		elsif number < 1_000_000_000
			sprintf '%.1f млн', number.to_f / 1_000_000
		else
			sprintf '%.1f млрд', number.to_f / 1_000_000_000
		end
	end
end

class Rewriter
	def initialize(options)
		@options = options
		@wc = MediaWiki::Gateway.new('http://ru.wikipedia.org/w/api.php')
		@wc.login(BOT_LOGIN, BOT_PASSWORD)

		@log = Logger.new($stdout)
		@log.level = @options[:verbose] ? Logger::INFO : Logger::WARN
	end

	def run(grabber, tmpl, list)
		processor = Processor.new(grabber, tmpl)
		File.open(list).each_line { |title|
			title.chomp!
			t = title.gsub(/ /, '_')
			@log.info "#{t} - #{grabber.class.to_s} - processing"

			src = @wc.get(t)
			@log.info "#{t} - #{grabber.class.to_s} - downloaded Wikipedia article"

			begin
				dest = processor.process(src)
			rescue Processor::NoDataFromGrabber
				@log.warn "#{t} - #{grabber.class.to_s} - got no data from external web analytics system"
				next
			rescue Processor::NoTemplateFound
				@log.warn "#{t} - #{grabber.class.to_s} - unable to match & update template"
				next
			end

			if src != dest
				confirmed = @options[:auto] ? true : manual_confirmation(src, dest)
				if confirmed
					@wc.edit(t, dest, :summary => "Актуализирована #{tmpl}", :minor => 1)
					@log.info "#{t} - #{grabber.class.to_s} - updated Wikipedia article"
				else
					@log.warn "#{t} - #{grabber.class.to_s} - modification not confirmed"
				end
			else
				@log.warn "#{t} - #{grabber.class.to_s} - not modified"
			end
		}
	end

	def manual_confirmation(src, dest)
		File.open('page-before', 'w') { |f| f.write(src) }
		File.open('page-after', 'w') { |f| f.write(dest) }
		system("diff -u page-before page-after")
		print 'Confirm? (y/n) '
		answer = gets
	end
end


options = {}
OptionParser.new { |opts|
	opts.banner = "Usage: #{__FILE__} [options]"

	opts.on('-a', '--[no-]auto', 'Run in full auto, skip any confirmations') { |v| options[:auto] = v }
	opts.on('-v', '--[no-]verbose', 'Verbose logging') { |v| options[:verbose] = v }

	opts.on_tail('-h', '--help', 'Show this message') { puts opts; exit }
}.parse!

rw = Rewriter.new(options)
#	'Шаблон:Посещаемость_по_данным_Compete',
rw.run(Openstat.new, 'посещаемость по данным Openstat', 'lists/Шаблон:Посещаемость_по_данным_Openstat')
rw.run(LiveInternet.new, 'посещаемость по данным LiveInternet', 'lists/Шаблон:Посещаемость_по_данным_LiveInternet')
rw.run(MailRu.new, 'посещаемость по данным Mail.ru', 'lists/Шаблон:Посещаемость_по_данным_Mail.ru')
rw.run(Rambler.new, 'посещаемость по данным Rambler', 'lists/Шаблон:Посещаемость_по_данным_Rambler')
rw.run(Quantcast.new, 'посещаемость по данным Quantcast', 'lists/Шаблон:Посещаемость_по_данным_Quantcast')
