#!/usr/bin/env ruby
# -*- coding: utf-8 -*-

require 'cgi'
require 'json'

$LOAD_PATH << '../get-analytics'
$LOAD_PATH << File.dirname(__FILE__)

require 'grabber/liveinternet'
require 'grabber/openstat'

require 'config'

require 'media_wiki'

class Processor
	COMMENT = '<!-- обновляется ежемесячно ботом -->'

	def initialize(grabber, tmpl)
		@grabber = grabber
		@tmpl = tmpl
	end

	def process(src)
		src.gsub(/\{\{\s*#{@tmpl}\s*\|\s*([^{}|]+?)\s*\}\}/m) { |x|
			id = $1
			stat = @grabber.run_id(id)

			# Check that we've got data we need
			unless stat[:visitors_mon]
				warn "#{@grabber.class.to_s} returned no data"
				return src
			end

			"{{#{@tmpl}|#{id}|#{humanize(stat[:visitors_mon])} посетителей/месяц #{COMMENT}}}"
		}
	end

	def humanize(number)
		if number < 1_000
			number.to_s
		elsif number < 1_000_000
			sprintf '%.1f тыс.', number.to_f / 1_000
		elsif number < 1_000_000_000
			sprintf '%.1f млн', number.to_f / 1_000_000
		else
			sprintf '%.1f млрд', number.to_f / 1_000_000_000
		end
	end
end

class Rewriter
	def initialize
		@wc = MediaWiki::Gateway.new('http://ru.wikipedia.org/w/api.php')
		@wc.login(BOT_LOGIN, BOT_PASSWORD)
	end

	def run(grabber, tmpl, list)
		processor = Processor.new(grabber, tmpl)
		File.open(list).each_line { |title|
			title.chomp!
			t = title.gsub(/ /, '_')
			src = @wc.get(t)
			dest = processor.process(src)

			if src != dest
				if $manual
					File.open('page-before', 'w') { |f| f.write(src) }
					File.open('page-after', 'w') { |f| f.write(dest) }
					system("kdiff3 page-before page-after")
				end
				@wc.edit(t, dest, :summary => "Актуализирована посещаемость по данным #{tmpl}", :minor => true)
			else
				warn "#{t} - not modified by #{processor.class.to_s}"
			end
		}
	end
end

$manual = true if ARGV[0] == '--manual'

rw = Rewriter.new
rw.run(LiveInternet.new, 'посещаемость по данным LiveInternet', "lists/Шаблон:Посещаемость_по_данным_LiveInternet")
rw.run(Openstat.new, 'посещаемость по данным Openstat', "lists/Шаблон:Посещаемость_по_данным_Openstat")
